swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get all transactions for the current month
      description: API for retrieving all transactions for the current month.
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get detailed information about a transaction
      description: API for retrieving detailed information about a specific transaction
      parameters:
        - in: path
          name: id
          description: The unique identifier of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /transactions/{id}/extra-info:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update extra information for a transaction
      description: API for updating existing information on a transaction
      parameters:
        - in: path
          name: id
          description: The unique identifier of the transaction
          required: true
          type: integer
        - in: body
          name: body
          description: Updated extra information payload
          required: true
          schema:
            $ref: '#/definitions/ExtraInfo'
      produces:
        - application/json
      responses:
        '200':
          description: Extra information updated successfully
          schema:
            type: object
            properties:
              montantCompte:
                type: number
                format: float
                example: 2500.75
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: integer
        example: 123
      montant:
        type: number
        format: float
        example: 500.75
      description:
        type: string
        example: 'Payment for services'

  TransactionDetails:
    type: object
    properties:
      id:
        type: integer
        example: 123
      montant:
        type: number
        format: float
        example: 500.75
      description:
        type: string
        example: 'Payment for services'

  ExtraInfo:
    type: object
    properties:
      commentaire:
        type: string
        example: 'This is an additional comment'

  TransactionExtraInfoResponse:
    type: object
    properties:
      montantCompte:
        type: number
        format: float
        example: 2500.75

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
