swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transactions
      summary: Get all transactions for the current month
      description: API for retrieving all transactions for the current month. You can filter transactions with query parameters for the date range.
      parameters:
        - in: query
          name: startDate
          description: Start date of the month in ISO format (optional)
          required: false
          type: string
          format: date
        - in: query
          name: endDate
          description: End date of the month in ISO format (optional)
          required: false
          type: string
          format: date
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{id}:
    get:
      tags:
        - Transactions
      summary: Get detailed information about a transaction
      description: API for retrieving detailed information about a specific transaction
      parameters:
        - in: path
          name: id
          description: The unique identifier of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{id}/extra-info:
    post:
      tags:
        - Transactions
      summary: Add extra information to a transaction
      description: API for adding new information to an existing transaction
      parameters:
        - in: path
          name: id
          description: The unique identifier of the transaction
          required: true
          type: integer
        - in: body
          name: body
          description: Extra information payload
          required: true
          schema:
            $ref: '#/definitions/ExtraInfo'
      produces:
        - application/json
      responses:
        '200':
          description: Extra information added successfully
          schema:
            $ref: '#/definitions/TransactionExtraInfoResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions
      summary: Update extra information for a transaction
      description: API for updating existing information on a transaction
      parameters:
        - in: path
          name: id
          description: The unique identifier of the transaction
          required: true
          type: integer
        - in: body
          name: body
          description: Updated extra information payload
          required: true
          schema:
            $ref: '#/definitions/ExtraInfo'
      produces:
        - application/json
      responses:
        '200':
          description: Extra information updated successfully
          schema:
            $ref: '#/definitions/TransactionExtraInfoResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Transactions
      summary: Delete extra information from a transaction
      description: API for deleting extra information from a transaction
      parameters:
        - in: path
          name: id
          description: The unique identifier 
